settings:
  username: "Kathund"
  commit_msg: "Update README with the recent activity"
  readme-file: ./README.md
  max_lines: 5
  disabled_events:
    - "comments"
  
  date:
    text: "Last Updated: {DATE} (GMT)"
